"""Add DeviceType.display_name

Revision ID: 084ffe73e89a
Revises: 25659351606b
Create Date: 2021-04-30 08:04:33.139574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '084ffe73e89a'
down_revision = '25659351606b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_type', sa.Column('display_name', sa.Text(), nullable=True, comment='Name to show in user interfaces'))
    op.alter_column('device_type', 'name',
               existing_type=mysql.TEXT(),
               comment='Short name to uniquely identify the device type',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_type', 'name',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Short name to uniquely identify the device type',
               existing_nullable=True)
    op.drop_column('device_type', 'display_name')
    # ### end Alembic commands ###
