"""remove activation_token from device

Revision ID: 1a4daeee9269
Revises: 9443f1256ebf
Create Date: 2022-06-01 10:46:36.567527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a4daeee9269'
down_revision = '9443f1256ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'name',
               existing_type=mysql.TEXT(),
               comment='Short name to uniquely identify the device',
               existing_nullable=False)
    op.drop_index('proof_of_presence_id', table_name='device')
    op.drop_column('device', 'activation_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('activation_token', mysql.TEXT(), nullable=False, comment='Unique, random token to identify the device during activation'))
    op.create_index('proof_of_presence_id', 'device', ['activation_token'], unique=True)
    op.alter_column('device', 'name',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Short name to uniquely identify the device',
               existing_nullable=False)
    # ### end Alembic commands ###
