"""Add device name

Revision ID: 6e528df2f1a5
Revises: 60d9bf1bc04e
Create Date: 2021-06-06 14:51:08.770965

"""
from alembic import op
from sqlalchemy.sql.expression import text
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e528df2f1a5'
down_revision = '60d9bf1bc04e'
branch_labels = None
depends_on = None


def upgrade():
    # Add device name; for existing device, set a random name.
    op.add_column('device', sa.Column('name', sa.Text(), server_default=text('CONCAT("TWOMES-", LPAD(FLOOR(RAND() * 1000000), 6, 0))'), nullable=False, comment='Short name to uniquely identify the device'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'device', ['name'])
    op.create_unique_constraint(None, 'device_type', ['display_name'])
    # ### end Alembic commands ###


def downgrade():
    op.drop_constraint('display_name', 'device_type', type_='unique')
    op.drop_constraint('name', 'device', type_='unique')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'name')
    # ### end Alembic commands ###
