"""nullable device.activation_token

Revision ID: d3a7edad6057
Revises: 9443f1256ebf
Create Date: 2022-06-09 11:38:04.133936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3a7edad6057'
down_revision = '9443f1256ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'activation_token',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='Unique, random token to identify the device during activation')
    op.alter_column('device', 'name',
               existing_type=mysql.TEXT(),
               comment='Short name to uniquely identify the device',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'name',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='Short name to uniquely identify the device',
               existing_nullable=False)
    op.alter_column('device', 'activation_token',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_comment='Unique, random token to identify the device during activation')
    # ### end Alembic commands ###
